name: Download TLE File

permissions:
  contents: write
  
on:
  schedule:
    # Runs at hourly
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  download_tle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download TLE file with timestamp
        run: |
          # Get current UTC time formatted as YYYY-MM-DDTHH-MM-SSZ
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H-%M-%SZ')
          echo "Timestamp: $TIMESTAMP"
          
          # Ensure the archive folder exists
          mkdir -p tle_archive
          
          # Download the TLE file from the URL and save it with the timestamped name
          FILE_PATH="tle_archive/tle-${TIMESTAMP}.txt"
          curl -sSf "https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=tle" -o "$FILE_PATH"
          echo "Downloaded file saved as $FILE_PATH"

      - name: Commit and push new TLE file
        run: |
          # Set git user information for the commit
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add changes (the new file) to git
          git add tle_archive/
          
          # Commit the changes; if there are no changes to commit, do nothing
          git commit -m "Add TLE file: $(date -u +'%Y-%m-%dT%H-%M-%SZ')" || echo "No changes to commit"
          
          # Push the commit back to the repository using the provided GITHUB_TOKEN
          git push
